apiVersion: v1
kind: Service
metadata:
  name: mybraincategorysapi-service
  namespace: mybrain
  labels:
    name: mybraincategorysapi-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: mybraincategorysapi
  type: ClusterIP